### ISSUE TITLE
The calculator is broken

### ISSUE THREAD

**Issue by ayaka14732** [pulipulichen/HTML5-Chi-Square-Test-of-Independence-Calculator#1]
Thanks for this great project! I have been using the calculator for a long time. However, recently, when I open the calculator, the result is not shown, and there are many errors in the console.

```
Uncaught ReferenceError: tinyMCE is not defined
ResponsiveVoice missing API key. See https://responsivevoice.org/register?devtools=https%3A%2F%2F…hub.io%2FHTML5-Chi-Square-Test-of-Independence-Calculator%2F
```

**Comment by pulipulichen** [comment]
@ayaka14732 
The problem is fixed now.
Thank you for your report.
